// Static content - no database required. Edit this file directly to add/change/remove
// projects, certificates, or experience entries. Each item needs a unique "_id" (just
// any short unique text, like "p1", "p2").

export const staticProjects = [
  {
    _id: 'p1',
    title: 'Smart Onion Storage Monitoring System',
    description:
      'Designed and deployed an IoT-based storage monitoring system using ESP32 and environmental sensors to monitor humidity, temperature, light, and gas levels across warehouse environments. Integrated a ThingSpeak cloud dashboard delivering live alerts and analytics, eliminating manual inspection cycles by automating spoilage risk detection.',
    technologies: ['ESP32', 'IoT Sensors', 'ThingSpeak', 'Cloud Dashboard'],
    category: 'IoT',
    date: '2026-01-01',
    githubLink: '',
    liveDemo: '',
    image: '/projects/onion.jpeg',
  },
  {
    _id: 'p2',
    title: 'Smart Plant Watering System',
    description:
      'Built an automated crop irrigation system using Arduino UNO and soil moisture sensors that triggers precise watering cycles only when needed, reducing water usage by up to 30%. Integrated a real-time Blynk cloud dashboard for remote soil condition monitoring, maintaining stable operation across 10+ test scenarios.',
    technologies: ['Arduino UNO', 'IoT Sensors', 'Blynk', 'Cloud Dashboard'],
    category: 'IoT',
    date: '2025-01-01',
    githubLink: '',
    liveDemo: '',
    image: '/projects/smart-plant.jpeg',
  },
  {
    _id: 'p3',
    title: 'Wireless RC Car',
    description:
      'Engineered a remotely controlled car using ESP32 supporting both Bluetooth and Wi-Fi communication protocols, achieving stable wireless control at 15m range. Implemented MQTT for Wi-Fi control mode enabling low-latency command transmission, validated across 50+ functional and stress tests.',
    technologies: ['ESP32', 'Bluetooth', 'Wi-Fi', 'MQTT'],
    category: 'Embedded Systems',
    date: '2024-01-01',
    githubLink: '',
    liveDemo: '',
    image: '/projects/wireless-car.jpeg',
  },
];

export const staticCertificates = [
  { _id: 'c17', title: 'Agile Scrum in Pratice', organization: 'Infosys Springboard', date: '2026-04-06', category: 'AI/ML', certificateLink: '/certificates/Agile Scrum in Practice Certificate.pdf', image: '/certificates/scrum.jpeg' },
  { _id: 'c18', title: 'Artificial Intelligence', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/Artificial Intelligence Certificate.pdf', image: '/certificates/ai.avif' },
  { _id: 'c7', title: 'C Programming', organization: 'Infosys Springboard', date: '2025-02-20', category: 'Programming', certificateLink: '/certificates/C CERTIFICATE.pdf', image: 'certificates/C.jpg' },
  { _id: 'c3', title: 'Computer Vision', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/Computer Vision Certificate.pdf', image: '/certificates/images2.jpg' },
  { _id: 'c19', title: 'Data Science', organization: 'Infosys Springboard', date: '2026-04-01', category: 'AI/ML', certificateLink: '/certificates/Data Science Certificate.pdf', image: '/certificates/ds.jpg' },
  { _id: 'c1', title: 'Deep Learning', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/deep-learning.pdf', image: '/certificates/Deep_learning.jpg' },
  { _id: 'c2', title: 'Generative AI Unleashing', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/generative-ai-unleashing.pdf', image: '/certificates/images1.jpeg' },
  { _id: 'c20', title: 'Generative Models for Developers', organization: 'Infosys Springboard', date: '2026-04-05', category: 'AI/ML', certificateLink: '/certificates/Generative models for  developers Certificate.pdf', image: '/certificates/genai.webp' },
  { _id: 'c13', title: 'HTML Certificate', organization: 'Great Learning', date: '2024-09-01', category: 'Programming', certificateLink: '/certificates/HTML CERTIFICATE.pdf', image: 'certificates/html.jpg' },
  { _id: 'c4', title: 'Natural Language Processing (NLP)', organization: 'Infosys Springboard', date: '2026-03-30', category: 'AI/ML', certificateLink: '/certificate/NLP certificate,pdf', image: '/certificates/images3.webp' },
  { _id: 'c21', title: 'OpenAI Generative Pre-trained Transformer 3 (GPT-3) for Developers', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/OpenAI Generative Pre-trained Transformer 3 (GPT-3) for developers Certificate.pdf', image: '/certificates/oai.webp' },
  { _id: 'c22', title: 'Principles of Generative AI', organization: 'Infosys Springboard', date: '2026-04-07', category: 'AI/ML', certificateLink: '/certificates/Principles of Generative AI Certification.pdf', image: '/certificates/gai.jpeg' },
  { _id: 'c5', title: 'Prompt Engineering', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/Prompt Engineering Certificate.pdf', image: '/certificates/pe.jpeg' },
  { _id: 'c6', title: 'Python Programming', organization: 'Infosys Springboard', date: '2026-04-01', category: 'Programming', certificateLink: '/certificates/PYTHON CERTIFICATE full.pdf', image: 'certificates/python.jpeg' },
  { _id: 'c23', title: 'Robotic Process Automation', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: '/certificates/Robotic Process Automation Certificate.pdf', image: '/certificates/rpa.jpg' },
  { _id: 'c8', title: 'Deloitte Australia – Cyber Security Job Simulation', organization: 'Forage', date: '2026-03-29', category: 'Virtual Internship', certificateLink: '/certificates/Deloitee Cyber.pdf', image: '/certificates/deloitte.webp' },
  { _id: 'c9', title: 'Deloitte Australia – Technology Job Simulation', organization: 'Forage', date: '2026-03-30', category: 'Virtual Internship', certificateLink: '/certificates/Deloitee Technology.pdf', image: '/certificates/deloitte.webp' },
  { _id: 'c10', title: 'Deloitte Australia – Data Analysis Job Simulation', organization: 'Forage', date: '2026-03-29', category: 'Virtual Internship', certificateLink: '/certificates/Deloitee Data Analysis.pdf', image: '/certificates/deloitte.webp' },
  { _id: 'c11', title: 'Tata Group – GenAI Data Analytics Job Simulation', organization: 'Forage', date: '2026-03-30', category: 'Virtual Internship', certificateLink: '/certificates/TATA GenAI Data Analytics.pdf', image: '/certificates/tata.png' },
  { _id: 'c12', title: 'Tata Group – Data Visualisation Job Simulation', organization: 'Forage', date: '2026-04-08', category: 'Virtual Internship', certificateLink: '/certificates/TATA Data Visualisation Certificate.pdf', image: 'certificates/tata.png' },
  { _id: 'c14', title: 'MATLAB Onramp', organization: 'MathWorks', date: '2025-01-08', category: 'MatLab', certificateLink: '/certificates/MATLAB ONRAMP CERTIFICATE.pdf', image: '/certificates/matlab.jpeg' },
  { _id: 'c15', title: 'Calculations on Grouped Data', organization: 'MathWorks', date: '2026-02-24', category: 'MatLab', certificateLink: '/certificates/MATLAB Calculations on grouped data.pdf', image: '/certificates/matlab.jpeg' },
  { _id: 'c16', title: 'Clean and Prepare Data for Analysis', organization: 'MathWorks', date: '2026-02-23', category: 'MatLab', certificateLink: '/certificates/MATLAB Clean and prepare Data for analysis.pdf', image: '/certificates/matlab.jpeg' },
  { _id: 'c27', title: 'Build with AI Bootcamp Coimbatore', organization: 'Google', date: '2026-06-26', category: 'Other', certificateLink: '/certificates/GDG BOOTCAMP.pdf', image: '/certificates/bwai.jpeg' },
  { _id: 'c24', title: 'IBM Dev Day Hackathon', organization: 'IBM', date: '2026-05-03', category: 'Other', certificateLink: '/certificates/IBM DEV DAY.pdf', image: '/certificates/ibm.Png' },
  { _id: 'c25', title: 'SDG Hackathon', organization: 'KSRCE', date: '2026-02-05', category: 'Other', certificateLink: '/certificates/SDG HACKATHON.pdf', image: '/certificates/sdg.jpg' },
  { _id: 'c26', title: 'Yukta25 Paper Presentation', organization: 'PSGiTech', date: '2025-03-15', category: 'Other', certificateLink: '/certificates/Yukta 2025 Certificates (Code Nexus).pdf-1.pdf', image: '/certificates/yukta.jpeg' },

];

export const staticExperience = [
  {
    _id: 'e1',
    title: 'AIVSC-2025 (All India Vayu Sainik Camp)',
    organization: 'National Cadet Corps (NCC)',
    type: 'NCC',
    description: 'Represented at the National-level NCC camp in Bangalore, selected among top cadets nationwide, demonstrating leadership, discipline, and teamwork.',
    startDate: '2025-06-01',
    endDate: '',
    location: 'Bangalore, India',
    link: '',
  },
  {
    _id: 'e2',
    title: 'IASC-2025 (State Level Camp)',
    organization: 'National Cadet Corps (NCC)',
    type: 'NCC',
    description: 'Represented at the State-level NCC camp, selected among top cadets statewide.',
    startDate: '2025-03-01',
    endDate: '',
    location: 'Tambaram, India',
    link: '',
  },
  {
    _id: 'e3',
    title: 'SDG Hackathon',
    organization: 'K.S.R. College of Engineering',
    type: 'Hackathon',
    description: 'Developed a solution addressing a Sustainable Development Goal in a competitive team environment.',
    startDate: '2025-08-01',
    endDate: '',
    location: 'Tiruchengode, India',
    link: '',
  },
  {
    _id: 'e4',
    title: 'Odoo x KAHE Virtual Hackathon',
    organization: 'Odoo x KAHE',
    type: 'Hackathon',
    description: 'Collaborated on an ERP-integrated application challenge.',
    startDate: '2025-09-01',
    endDate: '',
    location: 'Virtual',
    link: '',
  },
  {
    _id: 'e5',
    title: 'IBM Dev Day Bob Edition Virtual Hackathon',
    organization: 'IBM',
    type: 'Hackathon',
    description: 'Engaged with IBM Cloud technologies in a developer challenge.',
    startDate: '2025-10-01',
    endDate: '',
    location: 'Virtual',
    link: '',
  },
];
