// Static content - no database required. Edit this file directly to add/change/remove
// projects, certificates, or experience entries. Each item needs a unique "_id" (just
// any short unique text, like "p1", "p2").

export const staticProjects = [
  {
    _id: 'p1',
    title: 'Smart Onion Storage Monitoring System',
    description:
      'Designed and deployed an IoT-based storage monitoring system using ESP32 and environmental sensors to monitor humidity, temperature, light, and gas levels across warehouse environments. Int[...]',
    technologies: ['ESP32', 'IoT Sensors', 'ThingSpeak', 'Cloud Dashboard'],
    category: 'IoT',
    date: '2026-01-01',
    githubLink: '',
    liveDemo: '',
    image: '/projects/onion.jpeg',
  },
  {
    _id: 'p2',
    title: 'Smart Plant Watering System',
    description:
      'Built an automated crop irrigation system using Arduino UNO and soil moisture sensors that triggers precise watering cycles only when needed, reducing water usage by up to 30%. Integrated a[...]',
    technologies: ['Arduino UNO', 'IoT Sensors', 'Blynk', 'Cloud Dashboard'],
    category: 'IoT',
    date: '2025-01-01',
    githubLink: '',
    liveDemo: '',
    image: '/projects/smart-plant.jpeg',
  },
  {
    _id: 'p3',
    title: 'Wireless RC Car',
    description:
      'Engineered a remotely controlled car using ESP32 supporting both Bluetooth and Wi-Fi communication protocols, achieving stable wireless control at 15m range. Implemented MQTT for Wi-Fi cont[...]',
    technologies: ['ESP32', 'Bluetooth', 'Wi-Fi', 'MQTT'],
    category: 'Embedded Systems',
    date: '2024-01-01',
    githubLink: '',
    liveDemo: '',
    image: '/projects/wireless-car.jpeg',
  },
];

export const staticCertificates = [
  { _id: 'c17', title: 'Agile Scrum in Pratice', organization: 'Infosys Springboard', date: '2026-04-06', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Agile%20Scrum%20in%20Practice%20Certificate.pdf', image: '/certificates/scrum.jpeg' },
  { _id: 'c18', title: 'Artificial Intelligence', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Artificial%20Intelligence%20Certificate.pdf', image: '/certificates/ai.avif' },
  { _id: 'c7', title: 'C Programming', organization: 'Infosys Springboard', date: '2025-02-20', category: 'Programming', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/C%20CERTIFICATE.pdf', image: '/certificates/C.jpg' },
  { _id: 'c3', title: 'Computer Vision', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Computer%20Vision%20Certificate.pdf', image: '/certificates/images2.jpg' },
  { _id: 'c19', title: 'Data Science', organization: 'Infosys Springboard', date: '2026-04-01', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Data%20Science%20Certificate.pdf', image: '/certificates/ds.jpg' },
  { _id: 'c1', title: 'Deep Learning', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/deep-learning.pdf', image: '/certificates/Deep_learning.jpg' },
  { _id: 'c2', title: 'Generative AI Unleashing', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/generative-ai-unleashing.pdf', image: '/certificates/images1.jpeg' },
  { _id: 'c20', title: 'Generative Models for Developers', organization: 'Infosys Springboard', date: '2026-04-05', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Generative%20models%20for%20%20developers%20Certificate.pdf', image: '/certificates/genai.webp' },
  { _id: 'c13', title: 'HTML Certificate', organization: 'Great Learning', date: '2024-09-01', category: 'Programming', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/HTML%20CERTIFICATE.pdf', image: '/certificates/html.jpg' },
  { _id: 'c4', title: 'Natural Language Processing (NLP)', organization: 'Infosys Springboard', date: '2026-03-30', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/NLP%20certificate.pdf', image: '/certificates/images3.webp' },
  { _id: 'c21', title: 'OpenAI Generative Pre-trained Transformer 3 (GPT-3) for Developers', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/OpenAI%20Generative%20Pre-trained%20Transformer%203%20%28GPT-3%29%20for%20developers%20Certificate.pdf', image: '/certificates/oai.webp' },
  { _id: 'c22', title: 'Principles of Generative AI', organization: 'Infosys Springboard', date: '2026-04-07', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Principles%20of%20Generative%20AI%20Certification.pdf', image: '/certificates/gai.jpeg' },
  { _id: 'c5', title: 'Prompt Engineering', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Prompt%20Engineering%20Certificate.pdf', image: '/certificates/pe.jpeg' },
  { _id: 'c6', title: 'Python Programming', organization: 'Infosys Springboard', date: '2026-04-01', category: 'Programming', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/PYTHON%20CERTIFICATE%20full.pdf', image: '/certificates/python.jpeg' },
  { _id: 'c23', title: 'Robotic Process Automation', organization: 'Infosys Springboard', date: '2026-04-04', category: 'AI/ML', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Robotic%20Process%20Automation%20Certificate.pdf', image: '/certificates/rpa.jpg' },
  { _id: 'c8', title: 'Deloitte Australia – Cyber Security Job Simulation', organization: 'Forage', date: '2026-03-29', category: 'Virtual Internship', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Deloitee%20Cyber.pdf', image: '/certificates/deloitte.webp' },
  { _id: 'c9', title: 'Deloitte Australia – Technology Job Simulation', organization: 'Forage', date: '2026-03-30', category: 'Virtual Internship', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Deloitee%20Technology.pdf', image: '/certificates/deloitte.webp' },
  { _id: 'c10', title: 'Deloitte Australia – Data Analysis Job Simulation', organization: 'Forage', date: '2026-03-29', category: 'Virtual Internship', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Deloitee%20Data%20Analysis.pdf', image: '/certificates/deloitte.webp' },
  { _id: 'c11', title: 'Tata Group – GenAI Data Analytics Job Simulation', organization: 'Forage', date: '2026-03-30', category: 'Virtual Internship', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/TATA%20GenAI%20Data%20Analytics.pdf', image: '/certificates/tata.png' },
  { _id: 'c12', title: 'Tata Group – Data Visualisation Job Simulation', organization: 'Forage', date: '2026-04-08', category: 'Virtual Internship', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/TATA%20Data%20Visualisation%20Certificate.pdf', image: '/certificates/tata.png' },
  { _id: 'c14', title: 'MATLAB Onramp', organization: 'MathWorks', date: '2025-01-08', category: 'MatLab', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/MATLAB%20ONRAMP%20CERTIFICATE.pdf', image: '/certificates/matlab.jpeg' },
  { _id: 'c15', title: 'Calculations on Grouped Data', organization: 'MathWorks', date: '2026-02-24', category: 'MatLab', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/MATLAB%20Calculations%20on%20grouped%20data.pdf', image: '/certificates/matlab.jpeg' },
  { _id: 'c16', title: 'Clean and Prepare Data for Analysis', organization: 'MathWorks', date: '2026-02-23', category: 'MatLab', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/MATLAB%20Clean%20and%20prepare%20Data%20for%20analysis.pdf', image: '/certificates/matlab.jpeg' },
  { _id: 'c27', title: 'Build with AI Bootcamp Coimbatore', organization: 'Google', date: '2026-06-26', category: 'Other', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/GDG%20BOOTCAMP.pdf', image: '/certificates/bwai.jpeg' },
  { _id: 'c24', title: 'IBM Dev Day Hackathon', organization: 'IBM', date: '2026-05-03', category: 'Other', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/IBM%20DEV%20DAY.pdf', image: '/certificates/ibm.Png' },
  { _id: 'c25', title: 'SDG Hackathon', organization: 'KSRCE', date: '2026-02-05', category: 'Other', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/SDG%20HACKATHON.pdf', image: '/certificates/sdg.jpg' },
  { _id: 'c26', title: 'Yukta25 Paper Presentation', organization: 'PSGiTech', date: '2025-03-15', category: 'Other', certificateLink: 'https://raw.githubusercontent.com/JLobazRichit/portfolio-website/main/frontend/public/certificates/Yukta%202025%20Certificates%20%28Code%20Nexus%29.pdf-1.pdf', image: '/certificates/yukta.jpeg' },
];

export const staticExperience = [
  {
    _id: 'e1',
    title: 'AIVSC-2025 (All India Vayu Sainik Camp)',
    organization: 'National Cadet Corps (NCC)',
    type: 'NCC',
    description: 'Represented at the National-level NCC camp in Bangalore, selected among top cadets nationwide, demonstrating leadership, discipline, and teamwork.',
    startDate: '2025-09-18',
    endDate: '',
    location: 'Bangalore, India',
    link: '',
  },
  {
    _id: 'e2',
    title: 'IASC-2025 (State Level Camp)',
    organization: 'National Cadet Corps (NCC)',
    type: 'NCC',
    description: 'Represented at the State-level NCC camp, selected among top cadets statewide.',
    startDate: '2025-08-16',
    endDate: '',
    location: 'Tambaram, India',
    link: '',
  },
  {
    _id: 'e3',
    title: 'SDG Hackathon',
    organization: 'K.S.R. College of Engineering',
    type: 'Hackathon',
    description: 'Developed a solution addressing a Sustainable Development Goal in a competitive team environment.',
    startDate: '2026-02-05',
    endDate: '',
    location: 'Tiruchengode, India',
    link: '',
  },
  {
    _id: 'e4',
    title: 'Odoo x KAHE Virtual Hackathon',
    organization: 'Odoo x KAHE',
    type: 'Hackathon',
    description: 'Collaborated on an ERP-integrated application challenge.',
    startDate: '2026-05-10',
    endDate: '',
    location: 'Virtual',
    link: '',
  },
  {
    _id: 'e5',
    title: 'IBM Dev Day Bob Edition Virtual Hackathon',
    organization: 'IBM',
    type: 'Hackathon',
    description: 'Engaged with IBM Cloud technologies in a developer challenge.',
    startDate: '2026-05-03',
    endDate: '',
    location: 'Virtual',
    link: '',
  },
];
